version: "3.9"

services:
  web:
    build: .
    ports:
      - "127.0.0.1:3000:3000" # Sólo accesible desde el host (Nginx hace de proxy)
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
